"""File containing the LegalCategory enum"""

from enum import Enum

class LegalCategory(Enum):
    """Enum class for Legal category"""
    COMPETITION_LAW = "competition law"
    ANTI_CORRUPTION = "anti-corruption & anti-bribery"
    ARBITRATION_ADR = "arbitration & adr"
    ARBITRATION_LAW = "arbitration law"
    AVIATION = "aviation"
    BANKING_FINANCE = "banking & finance"
    BANKRUPTCY_INSOLVENCY = "bankruptcy & insolvency"
    BLOCKCHAIN_CRYPTOS = "blockchain & cryptos"
    CAPITAL_MARKETS = "capital markets"
    COMMERCIAL_LITIGATION = "commercial litigation"
    COMPETITION_ANTITRUST = "competition & antitrust"
    COMPLIANCE = "compliance"
    CORPORATE_COMMERCIAL = "corporate & commercial"
    CORPORATE_GOVERNANCE = "corporate governance"
    DATA_PROTECTION = "data protection"
    DISPUTE_RESOLUTION = "dispute resolution"
    ECOMMERCE = "e-commerce"
    EMPLOYMENT_HR = "employment and human resources"
    ENVIRONMENT = "environment"
    EXPORT_IMPORT_POLICIES = "export-import policies"
    FINTECH = "fintech"
    FUNDS = "funds"
    INBOUND_INVESTMENT = "inbound investment"
    INFRASTRUCTURE = "infrastructure"
    INSOLVENCY_LAW = "insolvency & bankruptcy law"
    INTELLECTUAL_PROPERTY = "intellectual property"
    INTERNATIONAL_TRADE = "international trade & bilateral investment treaties"
    JOINT_VENTURES = "joint ventures"
    LABOUR_EMPLOYMENT = "labour & employment"
    LEGAL_METROLOGY = "legal metrology law"
    LICENSING_FRANCHISING = "licensing & franchising"
    LITIGATION = "litigation"
    MEDIA_TELECOM = "media and telecommunications"
    MERGERS_ACQUISITIONS = "mergers & acquisitions"
    OIL_GAS = "oil & gas"
    POWER_ENERGY = "power & energy"
    PRIVATE_CLIENT = "private client"
    PRIVATE_EQUITY = "private equity"
    PROJECT_FINANCE = "project finance"
    REAL_ESTATE = "real estate"
    RESTRUCTURING_INSOLVENCY = "restructuring & insolvency"
    SECURITISATION_FINANCE = "securitisation & structured finance"
    SHIPPING = "shipping"
    STRUCTURED_FINANCE = "structured finance"
    SUCCESSION_PLANNING = "succession planning family office"
    TAXATION = "taxation"
    TECHNOLOGY = "technology"
    TMT_ECOMMERCE = "tmt and e-commerce"
    VENTURE_CAPITAL_FUNDS = "venture capital & funds"
    WHITE_COLLAR_CRIME = "white-collar crime"
